### ISSUE TITLE
Header image needs to be added properly

### ISSUE THREAD

**Issue by jonathanyeong** [code-newbies/trello_newsletter#4]
The newsletter currently checks if there is an image in the folder. If there is, it will return a **relative** link to the image. This relative link overwrites whatever is in the trello header image card. Otherwise it will just be a header text. 

However, we want to be able to link to an image url as well. This means we need to add the url to the trello card and actually read from it.

**Comment by jonathanyeong** [comment]
I fix the issue in this commit: a060e1ecb770b1aeec5df9b83f072efa332df86f. However, I do make one assumption:

If a file named "header_image.png" is found in the project folder this will be the image used in the newsletter. Otherwise, the url found on the trello card will be used. This means that when you create an image you don't need to upload it and then put the url in the trello card.  However, if someone else is generating the newsletter they can just use the image link found in the trello card.

What do you guys think?

**Comment by sarony** [comment]
@jonathanyeong this looks good! Also, mention me in these comments so I get a notification. I have general notifications from github turned off, so I didn't see this.

**Comment by jonathanyeong** [comment]
Yeah I probably should have mentioned something. I think I just put it up and hoped someone would read it. Will mention you next time @sarony. Closing this issue now!
